### PR TITLE
Use yaml C implementation when available

### PR DESCRIPTION
**Pull request by asottile**
I don't have any benchmarks except the testsuite, but that's a pretty good benchmark right?

### before
```
Ran 213 tests in 102.601s
```

### after
```
Ran 213 tests in 24.784s
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kddejong** [comment]
Seems a lot better. Thanks!

**Comment by asottile** [comment]
I can't see the build failure -- mind using a public service (such as travis-ci, etc.) such that the failure is visible?

**Comment by kddejong** [comment]
yea I can take a look into that.  You should be able to catch this with tox locally too.
```
************* Module cfnlint.cfn_yaml
C: 32, 4: Imports from package yaml are not grouped (ungrouped-imports)

------------------------------------
Your code has been rated at 10.00/10
```

**Comment by asottile** [comment]
oh I see `pylint36`

well this is a bit of a picky lint error, what does it want that _doesn't_ suck :'(

**Comment by cmmeyer** [comment]
Yeah -- we're exposing a few of the "expected errors" in our tests.  We should figure out a way to hide those, but I don't think it's been a priority.

Looks like it's that ungrouped thing -- trying to keep our 10/10 in pylint :)

**Comment by asottile** [comment]
I think this is a bug in pylint, going to open an issue there and locally disable that

**Comment by fatbasstard** [comment]
Nice performance gain! :+1:

**Comment by cmmeyer** [comment]
Approved! Preparing to merge.

A good follow up would be an output (via -d or some other mechanism) to show which parser is in use -- may help for to troubleshooting down the line.

**Pull request merged**
