### PR TITLE
Improved/simplified arguments and CommandLine usage

### PR DESCRIPTION
**Pull request by fatbasstard**
Improved and simplified the usage of cfn-lint. This PR tweaks the following:

- Made the temple the first default argument (positional argument). So cfn-lint can now be used with `cfn-lint template.yaml`. Still "optional", usage of `-t` or `--template` is still supported
- Added short argument options for all arguments (e.g. `-i` for `--ignore-checks`
- Grouped to arguments (in code) so all options are shown when the help is shown (`-h`)

Sample (new) output:

```
~  cfn-lint -h
usage: cfn-lint [-h] [-t TEMPLATE_ALT] [-b] [-d] [-f {quiet,parseable,json}]
                [-l] [-r [REGIONS [REGIONS ...]]]
                [-a [APPEND_RULES [APPEND_RULES ...]]]
                [-i [IGNORE_CHECKS [IGNORE_CHECKS ...]]] [-o OVERRIDE_SPEC]
                [-v] [-u]
                [template]

CloudFormation Linter

positional arguments:
  template              The CloudFormation template to be linted

optional arguments:
  -h, --help            show this help message and exit
  -t TEMPLATE_ALT, --template TEMPLATE_ALT
                        The CloudFormation template to be linted
  -b, --ignore-bad-template
                        Ignore failures with Bad template
  -d, --debug           Enable debug logging
  -f {quiet,parseable,json}, --format {quiet,parseable,json}
                        Output Format
  -l, --list-rules      list all the rules
  -r [REGIONS [REGIONS ...]], --regions [REGIONS [REGIONS ...]]
                        list the regions to validate against.
  -a [APPEND_RULES [APPEND_RULES ...]], --append-rules [APPEND_RULES [APPEND_RULES ...]]
                        specify one or more rules directories using one or
                        more --append-rules arguments.
  -i [IGNORE_CHECKS [IGNORE_CHECKS ...]], --ignore-checks [IGNORE_CHECKS [IGNORE_CHECKS ...]]
                        only check rules whose id do not match these values
  -o OVERRIDE_SPEC, --override-spec OVERRIDE_SPEC
                        A CloudFormation Spec override file that allows
                        customization
  -v, --version         Version of cfn-lint
  -u, --update-specs    Update the CloudFormation Specs
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cmmeyer** [comment]
Well, now that the subjects been broached, is it possible to make --template a default argument so that "cfn-lint template.yaml" works? :)

**Comment by fatbasstard** [comment]
Lemme check how that works in Python :P

**Comment by cmmeyer** [comment]
Ha! To be fair, you started it.  https://docs.python.org/3/library/argparse.html#default

**Comment by fatbasstard** [comment]
The `append_parser` messes it up a bit...... If you actually use the `-h` option, a lot of the arguments are not shown:

```
(venv) ➜  cfn-python-lint git:(arguments) cfn-lint -h
usage: cfn-lint [-h] [-t TEMPLATE] [-b] [-d {info,debug}]
                [-f {quiet,parseable,json}]

CloudFormation Linter

optional arguments:
  -h, --help            show this help message and exit
  -t TEMPLATE, --template TEMPLATE
                        CloudFormation Template
  -b, --ignore-bad-template
                        Ignore failures with Bad template
  -d {info,debug}, --log-level {info,debug}
                        Log Level
  -f {quiet,parseable,json}, --format {quiet,parseable,json}
                        Output Format
```

**Comment by kddejong** [comment]
We could fix that but would need to have a different strategy to merge template configuration items with the CLI parameters.

**Comment by cmmeyer** [comment]
This makes me happy! `cfn-lint simple-vpc.template.yml`

**Comment by fatbasstard** [comment]
I'd like to solve that in a different PR. Make it a separate thing

**Comment by cmmeyer** [comment]
So, move back to (-t,--template) for now and sort it out later? I'm ok with that.

**Pull request merged**
