### PR TITLE
Adding missing regions.

### PR DESCRIPTION
**Pull request by agamzn**
* Added Region: ap-northeast-3
* Added Region: eu-west-3

*Issue #, if available:* #461 

*Description of changes:*

- Adds missing region spec-files.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by agamzn** [comment]
Context: https://github.com/aws-quickstart/taskcat/pull/196

**Comment by kddejong** [comment]
thanks.  I was trying to keep an eye on that but dropped the ball.

**Comment by agamzn** [comment]
@kddejong  - done!

**Comment by agamzn** [comment]
@kddejong  - thinking the binary files are causing problems here. Can you think of anything else I should be looking for?

**Comment by kddejong** [comment]
Accidentally commented on the other PR. Oops. I’ll take a look at it shortly

**Comment by kddejong** [comment]
@agamzn sorry but updated your pull request to get this covered.  You can see the changes I made as they were really small.  I let the `cfn-lint --update-specs` download the specs for us

**Pull request merged**
