### PR TITLE
Add override spec mechanism

### PR DESCRIPTION
**Pull request by fatbasstard**
Add a simple mechanism to override/alter/customize the AWS Resource Specification.

Example:

```
{
  "PropertyTypes": {
    "AWS::S3::Bucket.WebsiteConfiguration": {
      "Properties": {
        "ErrorDocument": {
          "Required": true
        }
      }
    }
  },
  "ResourceTypes": {
    "AWS::S3::Bucket": {
      "Properties": {
        "BucketName": {
          "Required": true
        }
      }
    }
  }
}

```

This files makes the Bucketname required, just like the Errordocument
(if a WebsiteConfiguration is specified)

This gives people the ability to "customize" the linting rules. Say a company wants to enforce certain values to be specified (like `BucketName`, `Encryption` or `Tags`) this allows the overriding of the AWS specifications.

### CODE REVIEW

**Comment by fatbasstard** [comment]
Need to write some unit tests for this, but this is the general idea. Simple yet powerful

**Comment by fvanboven** [comment]
Would be nice to see the error output...

**Comment by kddejong** [comment]
Yea not sure how I can do that yet... Let me think on that.

Using config file /cfnlint/pylintrc
************* Module cfnlint.helpers
C: 55, 0: Missing function docstring (missing-docstring)
W: 69, 8: Redefining name 'region' from outer scope (line 52) (redefined-outer-name)
W: 92, 8: Redefining name 'region' from outer scope (line 52) (redefined-outer-name)
************* Module cfnlint.__main__
W:160, 0: Bad indentation. Found 16 spaces, expected 12 (bad-indentation)
W:161, 0: Bad indentation. Found 16 spaces, expected 12 (bad-indentation)
E:159,16: Module 'json.decoder' has no 'JSONDecodeError' member (no-member)

**Comment by kddejong** [comment]
Looks great to me.  Would love to see some tests.  Let me know if you need any help with writing tests.

**Comment by fatbasstard** [comment]
Having some dependency/flow struggles with the loading of all the Rules, The CloudSpec loading. Let me think about this...

(specs are loaded immediately into memory, the specs are used in the __init__ of some rules)

**Comment by kddejong** [comment]
@fatbasstard Yea not sure that makes sense anymore either.  Originally I had the individual rules loading the Specs so I put it into the __init__.  Then I moved the loading of the Specs into helpers so we didn't have those spec files being loaded across many different rules.  I'm not sure there is a good reason to keep those things in the init honestly.   Open to thoughts on that.

**Comment by fatbasstard** [comment]
Added a test, which also displays the Spec loading "issue". I'll think about refactoring, but for now got something

**Pull request merged**
